"use strict";
exports.__esModule = true;
var printaeu_js_1 = require("../dist/printaeu.js");
var warn = printaeu_js_1.Print.create();
warn.preAppend("".concat(printaeu_js_1.color.reset, "[").concat(printaeu_js_1.color.cyan, "DB").concat(printaeu_js_1.color.reset, "] [").concat(printaeu_js_1.color.yellow, "WARN").concat(printaeu_js_1.color.reset, "] "));
warn.setColorfulTimeStamp(false);
var info = printaeu_js_1.Print.create();
info.preAppend("".concat(printaeu_js_1.color.reset, "[").concat(printaeu_js_1.color.cyan, "DB").concat(printaeu_js_1.color.reset, "] [").concat(printaeu_js_1.color.cyan, "INFO").concat(printaeu_js_1.color.reset, "] "));
info.setColorfulTimeStamp(true);
warn.red('test');
info.inline.log('test');
process.exit();
printaeu_js_1.print.black('black');
printaeu_js_1.print.inline.red('red');
printaeu_js_1.print.green('green');
printaeu_js_1.print.yellow('yellow');
printaeu_js_1.print.blue('blue');
printaeu_js_1.print.magenta('magenta');
printaeu_js_1.print.cyan('cyan');
printaeu_js_1.print.white('white');
printaeu_js_1.print.gray('gray');
printaeu_js_1.print.grey('grey');
printaeu_js_1.print.pink('pink');
printaeu_js_1.print.orange('orange');
printaeu_js_1.print.bright.black('black');
printaeu_js_1.print.bright.red('red');
printaeu_js_1.print.bright.green('green');
printaeu_js_1.print.bright.yellow('yellow');
printaeu_js_1.print.bright.blue('blue');
printaeu_js_1.print.bright.magenta('magenta');
printaeu_js_1.print.bright.cyan('cyan');
printaeu_js_1.print.bright.white('white');
printaeu_js_1.print.bright.gray('gray');
printaeu_js_1.print.bright.grey('grey');
printaeu_js_1.print.bright.pink('pink');
printaeu_js_1.print.bright.orange('orange');
printaeu_js_1.print.dim.black('black');
printaeu_js_1.print.dim.red('red');
printaeu_js_1.print.dim.green('green');
printaeu_js_1.print.dim.yellow('yellow');
printaeu_js_1.print.dim.blue('blue');
printaeu_js_1.print.dim.magenta('magenta');
printaeu_js_1.print.dim.cyan('cyan');
printaeu_js_1.print.dim.white('white');
printaeu_js_1.print.dim.gray('gray');
printaeu_js_1.print.dim.grey('grey');
printaeu_js_1.print.dim.pink('pink');
printaeu_js_1.print.dim.orange('orange');
printaeu_js_1.print.italic.black('black');
printaeu_js_1.print.italic.red('red');
printaeu_js_1.print.italic.green('green');
printaeu_js_1.print.italic.yellow('yellow');
printaeu_js_1.print.italic.blue('blue');
printaeu_js_1.print.italic.magenta('magenta');
printaeu_js_1.print.italic.cyan('cyan');
printaeu_js_1.print.italic.white('white');
printaeu_js_1.print.italic.gray('gray');
printaeu_js_1.print.italic.grey('grey');
printaeu_js_1.print.italic.pink('pink');
printaeu_js_1.print.italic.orange('orange');
printaeu_js_1.print.reverse.black('black');
printaeu_js_1.print.reverse.red('red');
printaeu_js_1.print.reverse.green('green');
printaeu_js_1.print.reverse.yellow('yellow');
printaeu_js_1.print.reverse.blue('blue');
printaeu_js_1.print.reverse.magenta('magenta');
printaeu_js_1.print.reverse.cyan('cyan');
printaeu_js_1.print.reverse.white('white');
printaeu_js_1.print.reverse.gray('gray');
printaeu_js_1.print.reverse.grey('grey');
printaeu_js_1.print.reverse.pink('pink');
printaeu_js_1.print.reverse.orange('orange');
printaeu_js_1.print.inline.dim.black('black');
printaeu_js_1.print.inline.dim.red('red');
printaeu_js_1.print.inline.dim.green('green');
printaeu_js_1.print.inline.dim.yellow('yellow');
printaeu_js_1.print.inline.dim.blue('blue');
printaeu_js_1.print.inline.dim.magenta('magenta');
printaeu_js_1.print.inline.dim.cyan('cyan');
printaeu_js_1.print.inline.dim.white('white');
printaeu_js_1.print.inline.dim.gray('gray');
printaeu_js_1.print.inline.dim.grey('grey');
printaeu_js_1.print.inline.dim.pink('pink');
printaeu_js_1.print.inline.dim.orange('orange');
printaeu_js_1.print.setBg.cyan('magenta');
printaeu_js_1.print.cyan('hiiiiiii');
printaeu_js_1.print.clear();
printaeu_js_1.print.cyan('hiiiiiii2');
printaeu_js_1.print.bold.cyan('hiiiiiii2');
// print.toLog('ola', './teste.txt');
// print.toLog('nova linha');
// print.toLog('nova linha');
// print.toLog({locura: 'dado'});
